version: '3'
services:
  exchange-service:
    build: ./services/exchange

  web-client:
    build: ./clients/web

  ingress:
   image: nginx:alpine
   volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
   ports:
     - "80:80"
