version: '3'
services:
  exchange-service:
    build: ./services/exchange
    env_file: ./services/exchange/.env

  web-client:
    build: ./clients/web

  ingress:
   image: nginx:alpine
   volumes:
     - ./services/ingress/nginx.conf:/etc/nginx/nginx.conf
   ports:
     - "80:80"
