version: '3'
services:
  ingress:
   image: nginx:1.25.3-alpine
   volumes:
     - ./services/ingress/nginx.conf:/etc/nginx/nginx.conf
   ports:
     - "80:80"

  auth-service:
    build: ./services/auth
    env_file: ./services/auth/.env

  exchange-service:
    build: ./services/exchange
    env_file: ./services/exchange/.env

  web-client:
    build: ./clients/web

  users-service:
    build: ./services/users
